
export const FETCH_MEMO_LIST = {
    REQUEST : 'FETCH_MEMO_LIST_REQUEST',
    SUCCESS : 'FETCH_MEMO_LIST_SUCCESS',
    FAILURE : 'FETCH_MEMO_LIST_FAILURE',
} as const


export const FETCH_DELETED_MEMO_LIST = {
    REQUEST : 'FETCH_DELETED_MEMO_LIST_REQUEST',
    SUCCESS : 'FETCH_DELETED_MEMO_LIST_SUCCESS',
    FAILURE : 'FETCH_DELETED_MEMO_LIST_FAILURE',
}  as const




export const FETCH_MEMO = {
    REQUEST : 'FETCH_MEMO_REQUEST',
    SUCCESS : 'FETCH_MEMO_SUCCESS',
    FAILURE : 'FETCH_MEMO_FAILURE',
}  as const


export const FETCH_DELETED_MEMO = {
    REQUEST : 'FETCH_DELETED_MEMO_REQUEST',
    SUCCESS : 'FETCH_DELETED_MEMO_SUCCESS',
    FAILURE : 'FETCH_DELETED_MEMO_FAILURE',
}  as const


export const ADD_MEMO = {
    REQUEST : 'ADD_MEMO_REQUEST',
    SUCCESS : 'ADD_MEMO_SUCCESS',
    FAILURE : 'ADD_MEMO_FAILURE',
}  as const


export const DELETE_MEMO = {
    REQUEST : 'DELETE_MEMO_REQUEST',
    SUCCESS : 'DELETE_MEMO_SUCCESS',
    FAILURE : 'DELETE_MEMO_FAILURE',
}  as const



export const RESTORE_MEMO = {
    REQUEST : 'RESTORE_MEMO_REQUEST',
    SUCCESS : 'RESTORE_MEMO_SUCCESS',
    FAILURE : 'RESTORE_MEMO_FAILURE',
} as const





export const CLEAR_API_CALL_STATUS = 'CLEAR_API_CALL_STATUS' as const

export const SHOW_TOAST = 'SHOW_TOAST'as const
export const ADD_TOAST = 'ADD_TOAST'as const
export const REMOVE_TOAST = 'REMOVE_TOAST'as const

export const SHOW_DIALOG = 'SHOW_DIALOG'as const
export const CONFIRM_DIALOG = 'CONFIRM_DIALOG'as const
export const CANCEL_DIALOG = 'CANCEL_DIALOG'as const